[versions]
bungee = "1.21-R0.4"
spigot = "1.21.4-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
gson = "2.13.2"
guice = "7.0.0"
annotations = "26.0.2-1"
bstats = "3.1.0"
adventureTextMinimessage = "4.26.1"
adventureTextSerializerLegacy = "4.26.1"
adventureBungee = "4.4.1"
adventueBukkit = "4.4.1"
slf4j = "2.0.17"
logback = "1.5.22"
snakeYaml = "2.5"

[libraries]
bungee = { module = "net.md-5:bungeecord-api", version.ref = "bungee" }
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bstatsVelocity = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }
bstatsBungee = { module = "org.bstats:bstats-bungeecord", version.ref = "bstats" }
adventureTextMinimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventureTextMinimessage" }
adventureTextSerializerLegacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventureTextSerializerLegacy" }
adventureBungee = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventureBungee" }
adventureBukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventueBukkit" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
snakeYaml = { module = "org.yaml:snakeyaml", version.ref = "snakeYaml" }